language: objective-c
osx_image: xcode7.2b1
xcode_project: SwiftMongoDB.xcodeproj
xcode_scheme: SwiftMongoDB-OSX
before_install:
    - brew update
    - brew install carthage
install:
    - carthage bootstrap --verbose
script:
    - xcodebuild -project SwiftMongoDB.xcodeproj -scheme SwiftMongoDB-OSX test -sdk macosx | xcpretty -c
    - carthage build --no-skip-current
