language: objective-c
osx_image: xcode7.2b1
xcode_project: SwiftMongoDB.xcodeproj
xcode_scheme: SwiftMongoDB-OSX
before_install:
    - brew install mongodb
    - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.10/Carthage.pkg"
    - sudo installer -pkg "Carthage.pkg" -target /
    - rm "Carthage.pkg"
install:
    - carthage bootstrap --no-build
before_script:
    - mkdir /tmp/data
    - mongod --dbpath /tmp/data --bind_ip 127.0.0.1 &> /dev/null &
script:
    - xctool -project SwiftMongoDB.xcodeproj -scheme SwiftMongoDB-OSX clean build test -sdk macosx CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
    - bash <(curl -s https://codecov.io/bash)
