language: objective-c
osx_image: xcode7.2b1
xcode_project: SwiftMongoDB.xcodeproj
xcode_scheme: SwiftMongoDB-OSX
before_install:
    - brew update
    - brew install carthage
install:
    - set -o pipefail && carthage bootstrap --verbose --platform macosx,ios | xcpretty -c
script:
    - set -o pipefail && xcodebuild -project SwiftMongoDB.xcodeproj -scheme SwiftMongoDB-OSX test -sdk macosx | xcpretty -c
    - set -o pipefail && carthage build --platform macosx,ios --no-skip-current --verbose | xcpretty -c
